### ISSUE TITLE
Inserting / deleting multiple characters: API change

### ISSUE THREAD

**Issue by ajoslin** [noffle/hyper-string#2]
How were you thinking of doing insertion/deletion of a full string? 

It might require a breaking API change. It would make the most sense for the success callback passed in to be passed an array of operations, one for each character. Right now it just receives one op.

I can open a PR doing this change, just want to hear your thoughts on that.

**Comment by hackergrrl** [comment]
Yes, I've been meaning to add string-wise (batch) operations to the API: very open to this. It shouldn't be a breaking change though:

`insert` already takes a string, so the API would expand to just not ignoring the characters after the 1st.

`delete` could similarly be extended to accept a `count` before `cb`. It would step 4 characters through the result of `str.chars()` and issue 4 single character deletion ops to hyperlog.

Sound reasonable?

**Comment by ajoslin** [comment]
By breaking API change, I mean that with `insert`, `cb` currently receives `(err, op)`, but now it needs to receive `(err, arrayOfOps)`.

The other changes sound correct.
